name: Code quality

on: [push, pull_request]

jobs:
  code-quality:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run Prettier
        run: yarn prettier --write .

      - name: Run ESLint
        run: yarn eslint '**/*.(ts|js)?(x)' --report-unused-disable-directives
